spring.application.name=Api-Gateway

server.port=8443

spring.cloud.gateway.routes[0].id=order
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/pedidos/**
spring.cloud.gateway.routes[0].filters[0]=AddRequestHeader=X-Gateway-Authenticated,true

logging.level.org.springframework.cloud.gateway=DEBUG

management.endpoints.web.exposure.include=*

spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.sql.init.mode=always

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=senha123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=apigateway